name: erp_prototipo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  camera: ^0.11.1
  crypto: ^3.0.6
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.8.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  http: ^1.4.0
  image_picker: ^1.1.2
  mobile_scanner: ^7.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  sqflite: ^2.4.2
  syncfusion_flutter_charts: ^29.2.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
